### PR TITLE
Make car scenes

### PR DESCRIPTION
**Pull request by Dechode**
Make playable car scenes from existing models

### CODE REVIEW

**Comment by michurebmann** [comment]
i tested them all (few turns)!
its so cool how you match the character of the cars with the RPM/Torque curve and gear ratio!
ther 4wd rallys on the dirt track are serious fun!!!!

why do you have the high speed damping on 0 on some cars?
some cars collide with the dirt track road mesh... the cart for example.... (tested yesterday)

**Comment by Dechode** [comment]
I left hi speed damping to 0 on cars that are so old they probably didn't have them irl. Like the Historic FWD rally cars.

The collision shapes are currently just boxes. So they get stuck pretty easily, i know. The crosskarts collision shapes especially are all over the place atm. At some point should make a separate collision mesh / try how good colliders we can get with godots generated simplified convex collision siblings with little work to the meshes. I just tried and the low poly car packs cars do not work with generated collision siblings because headlights, spoilers, exhaust pipes etc. are all part of the same mesh. Maybe it would work if we were to separate these to their own meshes?

The cars all certainly start to feel unique. Still needs lots of work on the default setups though.

**Comment by Dechode** [comment]
Hmm i looked at the graph you made about the low/hi speed dampening, and it looks like the low speed damping is higher than high speed damping, but the force generated is still higher in hi speed damping:

image

And the equation is: 
low_speed_part + high_speed_part

so the low speed part is still there if hi speed is set to 0. 

I agree setting the center of gravity is not easy atm. But i am not sure how to remedy this. I am open to suggestions. Currently i just eyeball the CoG and test how it feels to drive. Not very scientific lol.

**Comment by michurebmann** [comment]
i mean no aditional damping force above treshold... sorry ;)

but a classic damper have just a linear line til nirvana, the hispeed should go the same way up as the low.
 the thing about hi speed is, the bumps on the road are way faster then steereing inputs, and above a certain treshold, the high speed should not add that many aditional damping per speed, so the car stay calm, but are stiff in steering and weighttransfer inputs

a classic damper cant lower the damping force ratio curve

**Comment by Dechode** [comment]
Ahh okay now i think i understand! Will to try those Historic FWD rally cars with hi speed dampening set to same as lo speed and probably make new default setups for them.

**Comment by Dechode** [comment]
I will merge this and the drivetrain fixes and update PR, and then make a new PR for the rest of car scenes and default setups with the new drivetrain params.

**Pull request merged**
