### PR TITLE
Feature lo/hi speed damping

### PR DESCRIPTION
**Pull request by michurebmann**
I made an initial draft for the implementation of high/low speed damping, take a look and give me feedback,
is not willing to merge just to discuss.

I used this paper as a orientation:
https://www.kwsuspensions.net/technology/valve_technology/5_way

in the tire-circle app there is an indicator that shows whether the low or high level is active.... green = low, red = height.

to get absolute damper speeds i had to implement the mm based suspension. the values no longer match the "original", you have to retune the car to achieve similar behavior.

I set the hi/lo threshold at 0.4m/s to be able to test the effect well. due to the oscillations in the tire system, a 0.1-0.2m/s setting as in the paper is difficult to test

i allready implemented it in the menues and resources.

KR Me

### CODE REVIEW

**Comment by michurebmann** [comment]
by the way, the roll bars have to be way lowered because of new calcs, i dont know if the values are right in dhis draw, i used 10 on both axles, i think i have it too high in this version....

**Comment by Dechode** [comment]
This feels very good and was needed! Thanks for the PR. 

Could you change the branch this will be merged to dev instead of main? So that all development goes to dev first and then later i will merge dev into main. I think you can change the target branch in this PR:s options / edit menu somewhere.

Could also make the car_params.gd default values for suspension work with new mm based suspension. They are still in the thousands because of the old N/m suspension.   

Other than that it is really good.

**Comment by michurebmann** [comment]
because i dont trust my self i configured your graph to verify the damping curve:
DampForceVerivication

I will refactor the damping in a seperate method an change the things you mentioned.

what about the hi-speed threshold?
is it ok in the tire recource but not exposed to the menue?

**Comment by michurebmann** [comment]
oh, the thing in the userapps.... i deleted it but then i switched back and forth between branches so i forget about it.

tested it on the track i made!!  just great feeling for a first draw! 
was driving with big smile on face and somthimes just lol'ed lake a mad man!

**Comment by Dechode** [comment]
Hmm i think the hi-speed threshold is good now, each car can have their own different suspension with different threshold but player cant change it. 

Once this is merged i should probably refactor all of the parameters so suspension would have suspension_params.gd resoure, diff would have diff_params.gd and so on. Right now suspension and wheel stuff are in the same parameters and diff dont have it at all.  

Graph looks good! Would be awesome at some point to have the graph tool draw all kinds of graphs like dampening, tire forces, engine torque and what not. 

I know the feeling! Had a big smile on my face on my first drive with the wheel as well! Feels pretty much what you would expect the wheel to feel like. Also tried your map and holy crap the main straight is fast! Speeds were over 300 kph with the retro open wheeler.

**Comment by michurebmann** [comment]
i could not finish it today because i dont know if i have a weird bug....

i do some math....
acording to this source:
https://www.qa1.net/tech-center/spring-rate-tech#:~:text=Springs%20should%20typically%20be%20compressed,rate%20spring%20(about%2025%25).

a street car should dive around 25% of its spring travel for resting.
kennys Rally car:
weight per wheel: 2500N (around) (i changed rally cars weight distribution to 50:50)
spring len: 150mm(0.15)
1/4 = 37.5mm
2500N/37.5mm = 66.66 N/mm
that one is corect, when i put in 67N/mm spring force it dives almost exact 1/4 of travel in

Damping force is just mm/s * x 

i set up the dampers acording to this source: (ls and hs the same value just to get a real world value)
i know, normally rebound is higher then bump, but just to get some real world values

mceclip3_1603209800

this would mean around 8 for bump and 5 for rebound.

The look and feel of the setting is great ingame and i think i done the math correct.

but no mather how high or low i set up the dampers, the tire indicator circles jump aroun 10x more then your damping setup.....

i have to look forther tomorrow....  have to go to bed....

**Comment by Dechode** [comment]
Did you try to increase the anti-roll bar rate? I think that might play a big role in how big the circle is.

**Comment by Dechode** [comment]
Oh i see. It happens, Still felt quite good haha

**Comment by michurebmann** [comment]
im basically ready... is it ok for you to first fix the git submodule issue so i can merge the new dev in to my feature bevore push?
or is it intended to use the ffb plugin as git submodule in the open-throttle source(for everyone who download it, it will not work now...)?

**Comment by michurebmann** [comment]
oh i saw the answer there....

**Comment by michurebmann** [comment]
sorry, i better dont mess up with the dev branch.... can you do merge it as it is for once?
i have a huge mess in my fork now..... after merge i will make a fresh new fork and try to set up the sub module correctly.

**Comment by Dechode** [comment]
Looks like some of the changes i made caused a merge conflict. I will try to resolve this tomorrow. Dont close this PR though yet until i have resolved this.

**Comment by Dechode** [comment]
Made the PR that fixes the merge conflict. Ill close this now.

**Pull request closed without merging**
