### PR TITLE
Implement Force Feedback effects

### PR DESCRIPTION
**Pull request by Dechode**

### CODE REVIEW

**Comment by michurebmann** [comment]
is it ready for test on windows?

**Comment by Dechode** [comment]
I left you email with drive link to compiled libraries and how to set them up. The SConsctruct  file still needs work so it can compile on windows. But i was able to compile it manually. Check the email for more instructions.

**Comment by michurebmann** [comment]
how i set it up....
setup

**Comment by Dechode** [comment]
What does your ffbplugin.gdextension file look like? You can open it with any text editor. Make sure the path to libffbplugin.dll is correct in the file.

**Comment by michurebmann** [comment]
[configuration]

entry_symbol = "ffb_library_init"

[libraries]

linux.64="res://ffb_plugin/Godot-FFB-SDL/bin/libffbplugin.linux.template_debug.x86_64.so"
windows.x86_64="res://ffb_plugin/Godot-FFB-SDL/bin/libffbplugin.windows.template_debug.x86_64.dll"

**Comment by Dechode** [comment]
And reloading the project does not help? I do not know then what happens here. I got similar errors when the path in the .gdextension file was wrong, but it seems fine to me.

**Comment by michurebmann** [comment]
i tested a lot.... delete the path to linux file, renamed it, restarted machine, delete the entry_symbol line....

**Comment by Dechode** [comment]
Could you try to put the SDL2.dll in to the same folder as the libffbplugin.dll is?

**Comment by Dechode** [comment]
hmm that is weird. You could still try to download the latest SDL2 binaries from : https://github.com/libsdl-org/SDL/releases/tag/release-2.26.5 and try again.
Have you ever compiled any C++ source code yourself before? Maybe you could be able to compile the plugin yourself and see if it works?

**Comment by michurebmann** [comment]
lol, i not even get the engine sound generator working you linked in your project (the rust thing)

are you a linux only user?

i will try, i have done some C coding for micro processors....
there is a lot of info around about it...

but could you explayn me how to get the engine sound generator working?

**Comment by Dechode** [comment]
I currently dont have Windows on my desktop pc but my crappy laptop has. However it does not support vulkan and i was not even able to get anything compiling on it. Some errors about bindings/extensions even though i generated them and specified the file in the scons command like this tutorial says: https://docs.godotengine.org/en/stable/tutorials/scripting/gdextension/gdextension_cpp_example.html. 

I actually dont remember how to build the enginesound application. I suppose 'cargo build' should do something as it is a Rust project.

**Comment by michurebmann** [comment]
you use visual studio? can you give me the complete solution? have no clue how to set up a existing "project" to compile as .dll
i only need the 3 files? fbb_plugin.cpp, fbb_plugin.h, gdlibrary.cpp?
which is the "main" file (entry point?)

**Comment by Dechode** [comment]
Check the gdextension example i linked above. It lists the required tools for compiling. For build system you need scons and for compiler you have choices. I cross-compiled the library to Windows from Linux with minGW. But you can use visual studio tools for building it. Lots of the documentation for building the engine itself on: https://docs.godotengine.org/en/stable/contributing/development/compiling/compiling_for_windows.html still are valid for gdextension as far as i know.

 You also need to build the godot-cpp bindings which then gets linked to the gdextension plugin. Again there is tutorial for this in the gdextension example tutorial linked in my previous comment. And make sure to be on the godot-4 branch of my ffb plugin. It should not have teh gdlibrary.cpp file but register_types.cpp and .h file.

**Comment by michurebmann** [comment]
OMG!
It works! and how!!!!
it realy works great!!!! i dont expected this!  it feels pretty good IMO!

you are a fucking genious!!!! even more my hero!

What is FrontForce and RearForce

i had a error i had to solve first, it cant find the inverted value....

had to hard code it in options menue so it starts whidout error. but then i was suprised that it does what a wheel have to do in a race game (more or less)

bug

**Comment by Dechode** [comment]
Oh i think the errors are  because of outdated options.tres file. I think i mentioned this in the email but not here, that i updated the config so you need to remove the old options.tres that Open Throttle makes. Somewhere in you user directory. Options manager now tries to read a variable from the options.tres but it does not exist yet. But when deleting the old resource, when Open Throttle is launched next time it will create a new one. There probably is a way to check if resources are valid but i have not though about it yet. 

Front force is the average self aligning torques of the front wheels and rear force is the average of self aligning torques in the rear wheels. Adding a bit rear force makes it feel a bit better imo.

**Comment by Dechode** [comment]
Do think this is good to merge to dev @michurebmann ? All of the options work and so on? For me at least all seem to work fine.

**Comment by michurebmann** [comment]
i would love to see it merged!
for me, all work pretty well!
the only thing i saw is, when you asign the wheel inputs, i have to set it to -1 to +1
and then i tried with xbox pad again and could not choose anything in the rang field, but was set to -1 to +1.
so i had to delet the options again to reset it.

but the ffb work well, imo

**Comment by Dechode** [comment]
Was the input range missing in this ffb-plugin branch you mean? Because i noticed it was lacking in dev, but i fixed in this PR. Or at least thought i fixed it.

**Comment by michurebmann** [comment]
ah ok, it was back in the dev branch when i noticed it.... then its ok.....

**Comment by Dechode** [comment]
Great! I will merge this

**Pull request merged**
